language: python

dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - sudo apt-get install pandoc

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install nbsphinx
  - pip install jupyter

script:
  - make docs
  - make test

after_success:
  - coveralls

notifications:
  - webhooks: https://coveralls.io/webhook
  - email: false
