language: python

dist: xenial

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install cython
  - sudo apt-get install pandoc
  - sudo apt-get install cmake
  - sudo apt-get install gfortran
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install libatlas-base-dev
  - git clone https://github.com/JohannesBuchner/MultiNest
  - cd MultiNest/build
  - cmake ..
  - make
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/build/tomasstolker/species/MultiNest/lib
  - cd ../..

install:
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install nbsphinx
  - pip install jupyter

script:
  - make docs
  - make test

after_success:
  - coveralls

notifications:
  - webhooks: https://coveralls.io/webhook
  - email: false
