language: python

dist: xenial

python:
  - 3.6
  - 3.7

install:
  - sudo apt-get install pandoc
  - pip install -r requirements.txt
  - pip install pytest-cov
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install nbsphinx
  - pip install jupyter
  - git clone https://github.com/JohannesBuchner/MultiNest
  - cd MultiNest/build
  - cmake ..
  - make

script:
  - make docs
  - make test

after_success:
  - coveralls

notifications:
  - webhooks: https://coveralls.io/webhook
  - email: false
